version: '3.7'
services:
  mongo:
    container_name: mongo
    image: 'bitnami/mongodb:latest'
    ports:
      - "27017:27017"    
    environment:
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_KEY: testingthis
      MONGODB_PRIMARY_HOST: mongo
      MONGODB_ADVERTISED_HOSTNAME: mongo
      MONGODB_ROOT_PASSWORD: mongopass
    volumes:
      - 'mongodb_master_data:/bitnami'

  mongosecondary:
    container_name: mongosecondary
    image: 'bitnami/mongodb:latest'
    depends_on:
      - mongo
    environment:
      MONGODB_REPLICA_SET_MODE: secondary
      MONGODB_REPLICA_SET_KEY: testingthis
      MONGODB_PRIMARY_HOST: mongo
      MONGODB_PRIMARY_PORT_NUMBER: 27017
      MONGODB_ADVERTISED_HOSTNAME: mongosecondary
      MONGODB_PRIMARY_ROOT_PASSWORD: mongopass

  mongo-express:
    container_name: mongo-express
    image: 'mongo-express:latest'
    ports:
      - '8080:8081'
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo, mongosecondary
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongopass
    links:
      - mongo:mongo
    depends_on: 
      - mongo
      - mongosecondary
    restart: always

volumes:
  mongodb_master_data:
    driver: local