version: '3.7'
services:
  mongo:
    container_name: mongo
    image: 'bitnami/mongodb:4.4'
    ports:
      - '27017:27017'
    environment:
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_KEY: testingthis
      MONGODB_INITIAL_PRIMARY_HOST: mongo
      MONGODB_INITIAL_PRIMARY_PORT_NUMBER: 27017
      MONGODB_ADVERTISED_HOSTNAME: mongo
      MONGODB_ROOT_PASSWORD: mongopass
    volumes:
      - 'mongodb_master_data:/bitnami'
  mongosecondary:
    container_name: mongosecondary
    image: 'bitnami/mongodb:4.4'
    depends_on:
      - mongo
    environment:
      MONGODB_REPLICA_SET_MODE: secondary
      MONGODB_REPLICA_SET_KEY: testingthis
      MONGODB_INITIAL_PRIMARY_HOST: mongo
      MONGODB_INITIAL_PRIMARY_PORT_NUMBER: 27017
      MONGODB_ADVERTISED_HOSTNAME: mongosecondary
      MONGODB_PRIMARY_ROOT_PASSWORD: mongopass
  mongo-express:
    container_name: mongo-express
    image: 'mongo-express:latest'
    ports:
      - '8080:8081'
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo, mongosecondary
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongopass
    links:
      - mongo:mongo
    depends_on:
      - mongo
      - mongosecondary
    restart: always
  redis:
    image: 'redis:latest'
    container_name: redis
    hostname: redis
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/data'
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - '8081:8081'
    depends_on:
      - redis
volumes:
  mongodb_master_data:
    driver: local
  redis_data:
    driver: local
