---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: indorphins-be
  labels:
    app: indorphins-be
spec:
  replicas: 2
  selector:
    matchLabels:
      app: indorphins-be
  template:
    metadata:
      labels:
        app: indorphins-be
    spec:
      containers:
      - name: indorphins-be
        image: 662730807386.dkr.ecr.us-east-1.amazonaws.com/indorphins:0.0.3
        ports:
        - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: "indorphins-be"
spec:
  selector:
    app: indorphins-be
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3001